version: '3.8'

services:
  master:
    image: postgres:15
    container_name: pg-master
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "55432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
      - ./master-init:/docker-entrypoint-initdb.d
    networks:
      - pgnet

  pg-replica-1:
    image: postgres:15
    container_name: pg-replica-1
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - replica_data_1:/var/lib/postgresql/data
    depends_on:
      - master
    command:
      - bash
      - -c
      - |
        until pg_isready -h master -p 5432 -U postgres; do
          echo "Waiting for master..."; sleep 2;
        done
        rm -rf /var/lib/postgresql/data/*
        export PGPASSWORD=replicator
        pg_basebackup -h master -U replicator -D /var/lib/postgresql/data -Fp -Xs -P -R
        chown -R postgres:postgres /var/lib/postgresql/data
        chmod 0700 /var/lib/postgresql/data
        echo "primary_conninfo = 'host=master port=5432 user=replicator password=replicator'" >> /var/lib/postgresql/data/postgresql.conf
        echo "hot_standby = on" >> /var/lib/postgresql/data/postgresql.conf
        exec postgres
    networks:
      - pgnet

  pg-replica-2:
    image: postgres:15
    container_name: pg-replica-2
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - replica_data_2:/var/lib/postgresql/data
    depends_on:
      - master
    command:
      - bash
      - -c
      - |
        until pg_isready -h master -p 5432 -U postgres; do
          echo "Waiting for master..."; sleep 2;
        done
        rm -rf /var/lib/postgresql/data/*
        export PGPASSWORD=replicator
        pg_basebackup -h master -U replicator -D /var/lib/postgresql/data -Fp -Xs -P -R
        chown -R postgres:postgres /var/lib/postgresql/data
        chmod 0700 /var/lib/postgresql/data
        echo "primary_conninfo = 'host=master port=5432 user=replicator password=replicator'" >> /var/lib/postgresql/data/postgresql.conf
        echo "hot_standby = on" >> /var/lib/postgresql/data/postgresql.conf
        exec postgres
    networks:
      - pgnet

volumes:
  master_data:
  replica_data_1:
  replica_data_2:

networks:
  pgnet:
